\benglish

# English abstract {.unnumbered}

The species monitoring programme [meetnetten.be](www.meetnetten.be) aims at collecting reliable information on priority species in Flanders.
It consists of a series of monitoring schemes which were designed by the Research Institute for Nature and Forest (INBO).
Species are counted by volunteers in a standardized way under the coordination of the NGO Natuurpunt.

This report shows the first results of the vascular plant monitoring schemes.
When comparing the total population size in Flanders for the periods 2016-2018 and 2019-2021 we see:

-   a (strong) increase for *Gentianella uliginosa*, *Orchis morio*, *Mentha pulegium*, *Juncus capitatus*, *Halimione pedunculata*, *Hammarbya paludosa*, and *Orchis purpurea*
-   a moderate increase for *Scorzonera humilis*, *Scirpus pungens*, *Platanthera bifolia* and *Ranunculus ololeucos*
-   a stable population size for *Stratiotes aloides*, *Carex diandra* and *Potamogeton coloratus*
-   a moderate decrease for *Wahlenbergia hederacea* and *Deschampsia setacea*
-   a (strong) decrease for *Orobanche rapum-genistae*, *Herminium monorchis*, *Scirpus triqueter*, *Eriophorum gracile*, *Potamogeton acutifolius*, *Bupleurum tenuissimum* and *Potamogeton compressus*

\eenglish
