<!-- hier komt de inhoudstafel bij pdf -->

\mainmatter

# Inleiding

Betrouwbare informatie over de toestand en trends van dier- en plantensoorten in Vlaanderen is van groot belang voor de onderbouwing van het Vlaamse soortenbeleid en voor de rapportage over de Natura 2000-soorten aan Europa [@adriaens_monitoring_2011].
Daarom ging in 2016 het project 'Langetermijn monitoring van beleidsrelevante soorten via meetnetten in Vlaanderen' (of kortweg de 'soortenmeetnetten') van start voor de opvolging van 80 Vlaamse en Europees prioritaire soorten [@westra_voortgangsrapport_2019].
Elk meetnet bestaat uit een aantal vooraf vastgelegde locaties, waar één soort of meerdere soorten via een gestandaardiseerde methode geteld worden [@de_knijf_monitoring_2014].

De soortenmeetnetten zijn een citizen science project, wat betekent dat vrijwilligers de tellingen uitvoeren.
Natuurpunt Studie staat in voor de coördinatie en aansturing van de vrijwilligers en het Instituut voor Natuur- en Bosonderzoek (INBO) verwerkt de telgegevens.
Het Agentschap voor Natuur en Bos (ANB) en het INBO staan samen in voor de financiering.
Voor de planning van de tellingen en het invoeren van gegevens werd het webportaal [meetnetten.be](https://www.meetnetten.be) ontwikkeld.

In dit rapport stellen we de eerste resultaten voor van de verschillende vaatplantenmeetnetten [@van_landuyt_monitoringsprotocol_2019].
We geven eerst wat achtergrond over het [ontwerp van de soortenmeetnetten] en de [analyse van de telgegevens].

```{r , eval = !html_output, results = 'asis'}

cat("Dit rapport bevat enkele interactieve figuren die alleen kunnen bekeken worden op de [website versie](https://inbo.github.io/soortenmeetnetten-plantenrapport-2023/) van dit rapport.")
```
