---
title: Resultaten van de plantenmeetnetten in Vlaanderen
subtitle: Periode 2016 - 2021
author:
  - name:
      given: Toon
      family: Westra
    email: toon.westra@inbo.be
    orcid: 0000-0003-2478-9459
    affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
    corresponding: true
  - name:
      given: Wouter
      family: Van Landuyt
    email: wouter.vanlanduyt@inbo.be
    orcid: 0000-0002-1915-4486
    affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  - name:
      given: Roosmarijn
      family: Steeman
    email: roosmarijn.steeman@natuurpunt.be
    affiliation: Natuurpunt Studie
  - name:
      given: Sam
      family: Van de Poel
    email: sam.vandepoel@natuurpunt.be
    orcid: 0000-0001-6251-3766
    affiliation: Natuurpunt Studie
  - name:
      given: Hans
      family: Van Calster
    email: hans.vancalster@inbo.be
    orcid: 0000-0001-8595-8426
    affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
reviewer:
  - name:
      given: Marc
      family: Pollet
    email: marc.pollet@inbo.be
    orcid: 0000-0001-5198-5928
    affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
year: 2023
doi: 10.21436/inbor.99216099
reportnr: 51
depotnr: D/2023/3241/392
cover_photo: image/purperorchis_wouter_van_landuyt.JPG
cover_description: Purperorchis (&copy; Wouter Van Landuyt)
embargo: 2023-11-22
lang: nl
style: INBO
floatbarrier: subsubsection
keywords: "meetnet; monitoring; vaatplanten; prioritaire soorten"
community: "inbo"
publication_type: report
funder: Research Institute for Nature and Forest (INBO)
rightsholder: Research Institute for Nature and Forest (INBO)
bibliography: references.bib
link-citations: TRUE
site: bookdown::bookdown_site
output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  INBOmd::epub_book: default
# Don't run the format below.
# Only required for RStudio to recognise the project as a bookdown project.
# Hence don't use 'Build all formats'.
  bookdown::dontrun: default
---

# Dankwoord {.unnumbered}

We wensen in de eerste plaats alle vrijwilligers te bedanken voor de vele tellingen die ze hebben uitgevoerd voor de plantenmeetnetten.
Frederic Piesschaert bedanken we voor de technische ondersteuning bij de invoer van de gegevens via meetnetten.be en de bevraging van de meetnetten‐databank.
We bedanken ook de actieve leden en ex‐leden van de stuurgroep van het project 'Langetermijn monitoring van beleidsrelevante soorten via mee‐netten in Vlaanderen': Bernard Van Elegem, Véronique Verbist, Samuel De Rycke, Koen Van Keer, Hannes Ledegen, Wouter Vanreusel, Marc Herremans, Maurice Hoffmann en Marc Pollet.
Ten slotte willen we Marc Pollet bedanken voor het kritisch nalezen van dit rapport.

# Samenvatting {.unnumbered}

Via de soortenmeetnetten ([meetnetten.be](www.meetnetten.be)) willen het Instituut voor Natuur‐ en Bosonderzoek (INBO) en het Agentschap voor Natuur en Bos (ANB) betrouwbare informatie verzamelen over prioritaire soorten in Vlaanderen.
Deze groep van prioritaire soorten omvat 28 vaatplanten, waarvan 3 Natura 2000-soorten (Europees prioritaire soorten) en 25 Vlaams prioritaire soorten.
De Natura 2000-soorten worden geteld door professionals van het INBO.
Alle Vlaams prioritaire soorten worden door vrijwilligers geteld onder coördinatie van Natuurpunt Studie.

De tellers passen een vastgelegde methode toe om de populatiegrootte te schatten voor elk meetnetlocatie.
Daarbij loopt de teller systematisch de meetnetlocatie af in trajecten die ongeveer 5 meter van elkaar liggen.
De teller legt elk groeiplaats vast met een GPS en schat de abundantie op basis van de FLORON-schaal.
De meetnetlocaties worden om de drie jaar geteld.

Dit rapport toont de eerste resultaten voor de soorten die door de vrijwilligers geteld worden.
Als we de totale populatiegroottes voor Vlaanderen vergelijken tussen de periodes 2016-2018 en 2019-2021 zien we:

-   een (sterke) toename voor duingentiaan, harlekijn, polei, koprus, gesteelde zoutmelde, veenmosorchis en purperorchis
-   een matige toename voor kleine schorseneer, stekende bies, welriekende nachtorchis en witte waterranonkel
-   een stabiele toestand voor krabbenscheer, ronde zegge en weegbreefonteinkruid
-   een matige afname voor klimopklokje en moerassmele
-   een (sterke) afname voor grote bremraap, honingorchis, kleine wolfsklauw, driekantige bies, slank wollegras, spits fonteinkruid, fijn goudscherm en plat fonteinkruid.

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = FALSE,
  error = FALSE,
  message = FALSE
)

library(conflicted)
library(tidyverse)
library(INBOtheme)
library(INBOmd)
library(n2khab)
library(sf)
library(crosstalk)
library(kableExtra)
library(plotly)
library(leaflet)
library(gridExtra)

conflicts_prefer(dplyr::filter())

if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 72)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}

html_output <- opts_knit$get("rmarkdown.pandoc.to") == "html"

functions_path <- fileman_up("soortenmeetnetten-analysis")

source(file.path(functions_path, "src/functions_smp.R"))

data_path <- "../data"

```

